# Generated by Django 4.1.3 on 2022-11-30 22:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('picture_url', models.TextField(max_length=150)),
                ('fun_facts', models.TextField(max_length=1000)),
                ('will_see', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_comments', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert', to='sharkapi.certification')),
                ('dive_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='sharkapi.divesite')),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diver', to='sharkapi.diver')),
            ],
        ),
        migrations.AddField(
            model_name='diver',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='sharkapi.skilllevel'),
        ),
        migrations.AddField(
            model_name='diver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignedDive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='sharkapi.diverequest')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='sharkapi.diver')),
            ],
        ),
    ]
