# Generated by Django 4.1.3 on 2022-12-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diver',
            name='skill_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='sharkapi.skilllevel'),
        ),
    ]
